#!/bin/sh

userresources="$XDG_CONFIG_HOME/X11/Xresources"
usermodmap="$XDG_CONFIG_HOME/X11/Xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

dunst &
picom &
xset s 30
export XSECURELOCK_PAM_SERVICE=system-auth
export XSECURELOCK_PASSWORD_PROMPT=time
export XSECURELOCK_COMPOSITE_OBSCURER=0
export MOZ_USE_XINPUT2=1
xss-lock -n /usr/lib/xsecurelock/auth_x11 --transfer-sleep-lock -- xsecurelock &
# xss-lock --transfer-sleep-lock -- xscreensaver-command --lock &
clipmenud &
export CM_LAUNCHER=rofi
export CM_HISTLENGTH=20
feh --no-fehbg --bg-fill ~/System_Files/desktops/desktop1.jpeg &
exec i3
